import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ReactNode } from "react";
import MapWithSidebarLayout from "@/app/mapWithSidebarLayout";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import EditorContextProvider from "@/app/contexts/editorContext/editorContextProvider";
import { ConvexClientProvider } from "@/app/utils/convexClientProvider";
import { ConvexAuthNextjsServerProvider } from "@convex-dev/auth/nextjs/server";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  map,
  sidebar,
}: {
  map: ReactNode;
  sidebar: ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AntdRegistry>
          <ConvexAuthNextjsServerProvider>
            <ConvexClientProvider>
              <EditorContextProvider>
                <MapWithSidebarLayout
                  map={map}
                  sidebar={sidebar}
                ></MapWithSidebarLayout>
              </EditorContextProvider>
            </ConvexClientProvider>
          </ConvexAuthNextjsServerProvider>
        </AntdRegistry>
      </body>
    </html>
  );
}
