name: Playwright Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
#    services:
#      convex:
#        image: ghcr.io/get-convex/convex-backend:latest
#        ports:
#          - 3210:3210
#        options: >-
#          --health-cmd "curl -f http://localhost:3210/healthz || exit 1"
#          --health-interval 10s
#          --health-timeout 5s
#          --health-retries 5
    env:
      CONVEX_URL: http://localhost:3210
      CONVEX_SELF_HOSTED_URL: http://localhost:3210
      CONVEX_DEPLOYMENT: anonymous:anonymous-city-sketch
      NEXT_PUBLIC_CONVEX_URL: http://localhost:3210
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Launch Convex
        run: |
          docker run --name convex -p 3120:3120 -d ghcr.io/get-convex/convex-backend:latest
          sleep 10
          docker exec convex ./generate_admin_key.sh > admin_key.txt
          echo "CONVEX_SELFHOSTED_ADMIN_KEY=$(cat admin_key.txt)" >> $GITHUB_ENV
      - name: Setup Convex
        run: |
          npx convex deploy
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Build application
        run: npm run build
      - name: Run Playwright tests
        run: npx playwright test
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
