name: Static Analysis
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  eslint-prettier:
    name: ESLint & Prettier
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install modules
        run: npm ci
      - name: Run ESLint
        run: npm run lint:ci
      - name: Run Prettier
        run: npm run format:ci
